apiVersion: apps/v1
kind: Deployment
metadata:
  name: stonks-deployment
  labels:
    app: stonks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stonks
  template:
    metadata:
      labels:
        app: stonks
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: service-symbols-db
          image: qoala101/stonks:service_symbols_db
          volumeMounts:
            - mountPath: "/app/bin/VOVA"
              name: task-pv-storage