#ifndef STONKS_NETWORK_NETWORK_JSON_SPECIALIZED_CONVERSIONS_H_
#define STONKS_NETWORK_NETWORK_JSON_SPECIALIZED_CONVERSIONS_H_

/**
 * @file
 */
 
namespace stonks::network {}

#endif  // STONKS_NETWORK_NETWORK_JSON_SPECIALIZED_CONVERSIONS_H_
