apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-uri-exposer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      label: app-uri-exposer
  template:
    metadata:
      labels:
        label: app-uri-exposer
    spec:
      containers:
        - name: app-uri-exposer-container
          image: qoala101/stk:service_app_uri_exposer
          args:
            - --expose_uri_interval=60000
            - --reattempt_interval=60000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: aws-secret-access-key

        - name: ngrok-container
          image: ngrok/ngrok:latest
          args:
            - http
            - ingress-nginx-controller
          env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ngrok-authtoken
