apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /buy_low_sell_high(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: static-services-service
                port:
                  name: blsh-port
          - path: /symbols_db(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: static-services-service
                port:
                  name: sdb-port
