apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
  labels:
    app: stonks
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
