apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  labels:
    app: stonks
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/data"