apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stonks-symbols-db-persistent-volume-claim
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi