apiVersion: v1
kind: PersistentVolume
metadata:
  name: stonks-persistent-volume
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/data"