apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symbols-db-persistent-volume-claim
  labels:
    app: stonks
    service: symbols-db
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi