apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: qoala101/stonks:test_app
      volumeMounts:
        - mountPath: "/app/bin/new_dir"
          name: task-pv-storage