name: build-linux

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libstdc++6

      - name: Build Conan Dependencies
        run: |
          pip install conan==1.60.0
          conan config set general.revisions_enabled=True
          conan install . --build=missing -pr=./conanprofile.txt -if ./build -s build_type=Release

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
