name: build-linux

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install conan==1.60.0
          conan install . --build=missing -pr=./conanprofile.txt -if ./build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
