name: build-linux

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Clang
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt-get install -y libc++-15-dev libc++abi-15-dev

      - name: Build Conan Dependencies
        run: |
          pip install conan==1.60.0
          conan config set general.revisions_enabled=True
          conan install . --build=missing -pr=./conanprofile.txt -if ./build -s build_type=Release -s andreasbuhr-cppcoro:compiler.libcxx=libc++

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
