name: ci

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: bash ./script/build_images_release.sh

      - name: Deploy on Kubernetes
        run: kubectl apply -f ./kubernetes/app-deployment.yaml
